// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJvVev0kw0U_XsPOzMZT07lT2SF_8O_o',
    appId: '1:1090123068958:web:49f100ad7455244ab9e00f',
    messagingSenderId: '1090123068958',
    projectId: 'pulsepoint-adaa9',
    authDomain: 'pulsepoint-adaa9.firebaseapp.com',
    storageBucket: 'pulsepoint-adaa9.firebasestorage.app',
    measurementId: 'G-E6TJRM2Q2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WT7mf8-cPt7JZIU6yyvBx7sKG8pdjdg',
    appId: '1:1090123068958:android:767bec1845dbab9db9e00f',
    messagingSenderId: '1090123068958',
    projectId: 'pulsepoint-adaa9',
    storageBucket: 'pulsepoint-adaa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-_oVBBKYnBJ3pyyU9xr7ewrUqKAbNzs',
    appId: '1:1090123068958:ios:ce0a3c357937fc2bb9e00f',
    messagingSenderId: '1090123068958',
    projectId: 'pulsepoint-adaa9',
    storageBucket: 'pulsepoint-adaa9.firebasestorage.app',
    iosBundleId: 'com.pulsepoint.pulsepoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-_oVBBKYnBJ3pyyU9xr7ewrUqKAbNzs',
    appId: '1:1090123068958:ios:ce0a3c357937fc2bb9e00f',
    messagingSenderId: '1090123068958',
    projectId: 'pulsepoint-adaa9',
    storageBucket: 'pulsepoint-adaa9.firebasestorage.app',
    iosBundleId: 'com.pulsepoint.pulsepoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeJvVev0kw0U_XsPOzMZT07lT2SF_8O_o',
    appId: '1:1090123068958:web:ac3413b7c65b0859b9e00f',
    messagingSenderId: '1090123068958',
    projectId: 'pulsepoint-adaa9',
    authDomain: 'pulsepoint-adaa9.firebaseapp.com',
    storageBucket: 'pulsepoint-adaa9.firebasestorage.app',
    measurementId: 'G-2DMJGC3QT4',
  );
}
